[package]
name = "resume_wizard_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
async-openai = "0.10.2"
dotenv = "0.15.0"
